const safx531Reinf = {
    COD_EMPRESA: '@',
    COD_ESTAB: '@',
    DATA_MOVTO: '@',
    IND_FIS_JUR: '5',
    COD_FIS_JUR: '',
    COD_DOCTO: 'REINF',
    NUM_DOCFIS: '@',
    SERIE_DOCFIS: '0',
    SUBSERIE_DOCFIS: '@',
    COD_OPERACAO: 'REINF',
    COD_DARF: '',
    IND_TIPO_REND: '3',
    IND_TP_PROC_ADJ: '2',
    NUM_PROC_ADJ: '12345',
    COD_SUSP: '234567890',
    VLR_DESP_JUD: '@',
    VLR_DESP_ADVOGADO: '@',
    DSC_NAT_REND: 'REINF',
    QTDE_MESES: '12',
    IND_ORIG_REC: '2',
    NUM_CNPJ_ORIG_REC: '@',
    DSC_PROC_JUD: '@',
    VLR_N_RETIDO_IR: '@',
    VLR_DEP_JUD_IR: '@',
    VLR_COMP_ANO_CAL_IR: '@',
    VLR_COMP_ANO_ANT_IR: '@',
    VLR_REND_EXIG_SUSP_IR: '@',
    VLR_BASE_SUSP_IR: '@',
    VLR_BASE_SUSP_CSLL: '@',
    VLR_N_CSLL: '@',
    VLR_DEP_CSLL: '@',
    VLR_BASE_SUSP_COFINS: '@',
    VLR_N_COFINS: '@',
    VLR_DEP_COFINS: '@',
    VLR_BASE_SUSP_PIS_PASEP: '@',
    VLR_N_PIS_PASEP: '@',
    VLR_DEP_PIS_PASEP: '@'
}

module.exports = safx531Reinf;
